; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; 共通設定（どの環境でも使うベースの設定）
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = madhephaestus/ESP32Encoder
; 一旦 src フォルダの中身をすべてビルド対象外にするベースの魔法
build_src_filter = +<*> -<.git/> -<.svn/> -<*>

; 🚀 ① main.cpp だけを動かす環境
[env:run_main]
build_src_filter = ${env.build_src_filter} +<main.cpp>

; 🚀 ② main2.cpp だけを動かす環境
[env:run_main2]
build_src_filter = ${env.build_src_filter} +<main2.cpp>

[env:run_main3]
build_src_filter = ${env.build_src_filter} +<main3.cpp>

[env:run_main4]
build_src_filter = ${env.build_src_filter} +<main4.cpp>

[env:run_main5]
build_src_filter = ${env.build_src_filter} +<main5.cpp>

[env:run_main6]
build_src_filter = ${env.build_src_filter} +<main6.cpp>
; （おまけ）今後 test_motor.cpp などが増えても、ここに追加していくだけ！
; [env:test_motor]
; build_src_filter = ${env.build_src_filter} +<test_motor.cpp>